name: terraform

on:
  - pull_request
env:
  working_directory: ./test
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init &&
           echo ${{env.working_directory}}
      working-directory: env.working_directory

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      working-directory: env.working_directory

    - uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const tfInitStatus = ${{steps.init.outputs.exitcode == 0}} ? ':x:' : ':white_check_mark:'
          const tfValidationStatus = ${{steps.validate.outputs.exitcode == 0}} ? ':x:' : ':white_check_mark:'
          const tfPlanStatus = ${{steps.plan.outputs.exitcode == 0}} ? ':x:' : ':white_check_mark:'

          const output = `${tfInitStatus} Terraform Initialization
          ${tfValidationStatus} Terraform Validation
          ${tfPlanStatus} Terraform Plan

          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>

          *User*: @${{ github.actor }}
          *Action*: \`${{ github.event_name }}\`
          *Working Directory*: \`${{ env.working_directory }}\`
          *Workflow*: \`${{ github.workflow }}\``;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
