name: terraform

on:
  - pull_request

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      env:
        tf_actions_working_dir: ./test

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: env.tf_actions_working_dir

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
      working-directory: env.tf_actions_working_dir

    - uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>

          *User*: @${{ github.actor }}
          *Action*: \`${{ github.event_name }}\`
          *Working Directory*: \`${{ env.tf_actions_working_dir }}\`
          *Workflow*: \`${{ github.workflow }}\``;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
